# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://thefuturepreneur.info
title: The Futurepreneur
email: thefuturepreneur.info@gmail.com
author: The Future of Careers - Innovate and Inspire
description: Empower your career with The Futurepreneur, the leading platform for exploring the latest career opportunities for the youth. Discover the most promising and unconventional career paths that will help you achieve your goals and aspirations. Let us guide you towards a brighter future by equipping you with the knowledge and tools you need to thrive in the ever-changing world of work.
copyright: 'Copyright &copy; 2023 The Futurepreneur. All Rights Reserved.'
credits: 'Credits: Using Landing Page, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Apply to be featured
    url: 
